### ISSUE TITLE
Check to see if we can get rid of json.net dependency

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.Persistence.ServiceFabric#36]
Connects to https://github.com/Particular/NServiceBus.Azure/issues/300

To avoid version conflicts with other libraries that use json.net, it would be better if we didn't

**Comment by danielmarbach** [comment]
That is a tricky one. We use JSON.NET to serialize the saga data. Saga Data is domain data that might be complex and might even require a specific json mapping in certain cases. I don't see how we can use for example Simple Json because with that the user would have no control to override the serialization behavior. I vote for closing this. For Saga persistence I think it is OK to have a dependency to JSON.NET

**Comment by SeanFeldman** [comment]
👍

**Comment by danielmarbach** [comment]
Closing based on @Scooletz and @SeanFeldman feedback
